CREATE TABLE H_CUSTOMER (
 H_CUSTOMER_NO UNIQUE(10) NOT NULL,
 H_COUPON_NO NUMBER NULL,
 H_CUSTOMER_NAME VARCHAR2(20) NOT NULL,
 H_CUSTOMER_PHONENUM CHAR(13) NOT NULL,
 H_CUSTOMER_EMAIL VARCHAR2(50) NULL,
 H_CUSTOMER_CONTENT VARCHAR(1000) NULL,
 H_CUSTOMER_PRICE NUMBER NULL,
 H_CUSTOMER_PLACE VARCHAR(20) NOT NULL,
 H_CUSTOMER_DATE DATE NOT NULL,
 H_CUSTOMER_TIME VARCHAR(10) NOT NULL
);

CREATE TABLE H_COUPON (
 H_COUPON_NO NUMBER NOT NULL,
 H_CUSTOMER_CONTENT VARCHAR2(100) NULL,
 H_CUSTOMER_SALE NUMBER NOT NULL
);

CREATE TABLE P_MEMBER (
 P_MEMBER_EMAIL VARCHAR(50) NOT NULL,
 P_COUPON_NO NUMBER NULL,
 P_MEMBER_NAME VARCHAR2(20) NOT NULL,
 P_MEMBER_PW VARCHAR2(20) NOT NULL,
 P_MEMBER_PHONENUM CHAR(13) NOT NULL
);

CREATE TABLE P_COLOR (
 P_COLOR_CODE VARCHAR2(20) NOT NULL,
 P_COLOR_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE P_RESULT (
 P_RESULT_NO NUMBER NOT NULL,
 P_COLOR_CODE VARCHAR2(20) NOT NULL,
 P_MEMBER_ID VARCHAR2(20) NOT NULL,
 P_COLOR_NO NUMBER NOT NULL,
 M_SEASONTONE_CATEGORY VARCHAR(30) NOT NULL,
 P_RESULT_CONTENT VARCHAR(100) NOT NULL
);

CREATE TABLE M_CUSTOMER (
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_SEASONTONE_NO NUMBER NULL,
 M_CUSTOMER_PW VARCHAR2(20) NOT NULL,
 M_CUSTOMER_NAME VARCHAR2(20) NOT NULL,
 M_CUSTOMER_PHONENUM CHAR(13) NOT NULL,
 M_CUSTOMER_BIRTH VARCHAR2(20) NOT NULL,
 M_CUSTOMER_EMAIL VARCHAR2(50) NOT NULL,
 M_CUSTOMER_ADDR VARCHAR2(100) NOT NULL,
 M_CUSTOMER_JOINDATE DATE NOT NULL,
 M_CUSTOMER_POINT NUMBER NULL,
 M_CUSTOMER_GRADE VARCHAR2(10) NULL,
 M_CUSTOMER_SUMPRICE NUMBER NULL,
 M_CUSTOMER_AGREE CHAR(1) NOT NULL
);

CREATE TABLE M_ORDER (
 M_ORDER_NO VARCHAR2(20) NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_ORDER_NAME VARCHAR2(20) NULL,
 M_ORDER_PHONENUM CHAR(13) NOT NULL,
 M_ORDER_ADDR VARCHAR2(100) NOT NULL,
 M_ORDER_PAYMENT VARCHAR2(10) NULL,
 M_ORDER_DATE DATE NULL,
 M_ORDER_TOTALPRICE NUMBER NULL,
 M_ORDER_DEPOSITPRICE NUMBER NULL
);

CREATE TABLE M_PRODUCT (
 M_PRODUCT_CODE UNIQUE VARCHAR2(20) NOT NULL,
 M_SEASONTONE_NO NUMBER NOT NULL,
 M_PRODUCT_CATEGORY NUMBER NOT NULL,
 M_PRODUCT_NAME UNIQUE VARCHAR2(30) NOT NULL,
 M_PRODUCT_COLOR VARCHAR2(10) NULL,
 M_PRODUCT_PRICE NUMBER NULL,
 M_PRODUCT_DISCOUNT NUMBER NULL,
 M_PRODUCT_INVENTORY NUMBER NULL,
 M_PRODUCT_REGDATE DEFAULT DATE NOT NULL,
 M_PRODUCT_IMAGE VARCHAR2(100) NULL
);

CREATE TABLE M_COUPON (
 M_COUPON_NO NUMBER NOT NULL,
 M_PRODUCT_CODE VARCHAR2(20) NULL,
 M_COUPON_COUNT NUMBER NULL,
 M_COUPON_DISCOUNT NUMBER NOT NULL,
 M_COUPON_CATEGORY NUMBER NULL,
 M_COUPON_ENDDATE DATE NULL
);

CREATE TABLE M_ASK (
 M_ASK_NO NUMBER NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_PRODUCT_CODE VARCHAR2(20) NULL,
 M_ASK_CATEGORY VARCHAR2(20) NOT NULL,
 M_ASK_TITLE VARCHAR2(100) NOT NULL,
 M_ASK_CONTENT VARCHAR(4000) NOT NULL,
 M_ASK_DATE DATE NOT NULL,
 M_ASK_PW VARCHAR2(20) NULL,
 M_ASK_PWCHECK CHAR(1) NOT NULL,
 M_ASK_IMAGE1 VARCHAR2(100) NULL,
 M_ASK_IMAGE2 VARCHAR2(100) NULL,
 M_ASK_ANSWERDONE CHAR(1) NOT NULL
);

CREATE TABLE M_REVIEW (
 M_REVIEW_NO NUMBER NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_PRODUCT_CODE VARCHAR2(20) NOT NULL,
 M_REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
 M_REVIEW_IMAGE1 VARCHAR2(100) NULL,
 M_REVIEW_IMAGE2 VARCHAR2(100) NULL,
 M_REVIEW_STAR NUMBER NOT NULL
);

CREATE TABLE M_DELIVERY (
 M_OPRDER_NO VARCHAR2(20) NOT NULL,
 M_DELIVERY_STATUS VARCHAR2(10) NOT NULL,
 M_DELIVERY_COMPANY VARCHAR2(20) NOT NULL,
 M_DELIVERY_STARTDATE DATE NOT NULL,
 M_DELIVERY_ENDDATE DATE NULL,
 M_DELIVERY_NO VARCHAR2(20) NULL
);

CREATE TABLE M_ORDERPROD (
 M_ORDERPROD_NO UNIQUE(10) NOT NULL,
 M_ORDER_NO VARCHAR2(20) NOT NULL,
 M_ORDERPROD_CODE VARCHAR(20) NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_ORDERPROD_COUNT NUMBER NULL,
 M_ORDERPROD_PRICE NUMBER NULL,
 M_ORDERPROD_CHECK CHAR(1) NOT NULL,
 M_ORDERPROD_REVIEWCHECK CHAR(1) NOT NULL
);

CREATE TABLE M_EVENT (
 M_EVENT_NO NUMBER NOT NULL,
 M_EVENT_TITLE VARCHAR2(100) NOT NULL,
 M_EVENT_CONTENT VARCHAR2(4000) NULL,
 M_EVENT_IMAGE VARCHAR2(100) NULL,
 M_EVENT_STARTDATE DATE NULL,
 M_EVENT_ENDDATE DATE NULL
);

CREATE TABLE M_PACKAGE (
 M_PACKAGE_NO NUMBER UNIQUE NOT NULL,
 M_PRODUCT_CODE VARCHAR2(20) NOT NULL,
 M_SEASONTONE_CATEGORY UNIQUE VARCHAR(30) NOT NULL,
 M_PRODUCT_CODE2 VARCHAR2(20) NULL,
 M_PRODUCT_CODE3 VARCHAR2(20) NULL,
 M_PRODUCT_CODE4 VARCHAR2(20) NULL,
 M_PACKAGE_ IMAGE VARCHAR2(20) NULL,
 M_PACKAGE _PRICE NUMBER NULL,
 M_PACKAGE_DISCOUNT NUMBER NULL
);

CREATE TABLE M_ADDRBOOK (
 M_ADDRBOOK_NO NUMBER NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_ADDRBOOK_NAME VARCHAR2(20) NOT NULL,
 M_ADDRBOOK_PHONENUM CHAR(13) NOT NULL,
 M_ADDRBOOK_ADDR VARCHAR2(100) NOT NULL
);

CREATE TABLE M_CUSTOMER_COUPON (
 Key NUMBER NOT NULL,
 M_CUSTOMER_ID VARCHAR2(20) NOT NULL,
 M_COUPON_NO NUMBER NOT NULL
);

CREATE TABLE M_SEASONTONE (
 M_SEASONTONE_NO NUMBER NOT NULL,
 M_SEASONTONE_SEASON VARCHAR2(20) NOT NULL,
 M _SEASONTONE_SPRING VARCHAR(20) NULL,
 M_SEASONTONE_SUMMER VARCHAR(20) NULL,
 M_SEASONTONE_FALL VARCHAR(20) NULL,
 M_SEASONTONE_WINTER VARCHAR(20) NULL,
 M_SEASONTONE_TONE VARCHAR2(20) NOT NULL,
 M_SEASONTONE_MUTE VARCHAR(20) NULL,
 M _SEASONTONE_BRIGHT VARCHAR(20) NULL,
 M_SEASONTONE_WARM VARCHAR(20) NULL,
 M_SEASONTONE_LIGHT VARCHAR(20) NULL
);



CREATE TABLE M_ANSWER (
 M_ANSWER_NO NUMBER NOT NULL,
 M_ASK_NO NUMBER NOT NULL,
 M_ANSWER_DATE DATE NOT NULL,
 M_ANSWER_CONTENT VARCHAR(4000) NOT NULL
);

ALTER TABLE H_CUSTOMER ADD CONSTRAINT PK_H_CUSTOMER PRIMARY KEY (
 H_CUSTOMER_NO,
 H_COUPON_NO
);

ALTER TABLE H_COUPON ADD CONSTRAINT PK_H_COUPON PRIMARY KEY (
 H_COUPON_NO
);

ALTER TABLE P_MEMBER ADD CONSTRAINT PK_P_MEMBER PRIMARY KEY (
 P_MEMBER_EMAIL,
 P_COUPON_NO
);

ALTER TABLE P_COLOR ADD CONSTRAINT PK_P_COLOR PRIMARY KEY (
 P_COLOR_CODE
);

ALTER TABLE P_RESULT ADD CONSTRAINT PK_P_RESULT PRIMARY KEY (
 P_RESULT_NO,
 P_COLOR_CODE,
 P_MEMBER_ID,
 P_COLOR_NO,
 M_SEASON_NO
);

ALTER TABLE M_CUSTOMER ADD CONSTRAINT PK_M_CUSTOMER PRIMARY KEY (
 M_CUSTOMER_ID,
 M_SEASONTONE_NO
);

ALTER TABLE M_ORDER ADD CONSTRAINT PK_M_ORDER PRIMARY KEY (
 M_ORDER_NO,
 M_CUSTOMER_ID,
 M_SEASONTONE_NO
);

ALTER TABLE M_PRODUCT ADD CONSTRAINT PK_M_PRODUCT PRIMARY KEY (
 M_PRODUCT_CODE,
 M_SEASONTONE_NO
);

ALTER TABLE M_COUPON ADD CONSTRAINT PK_M_COUPON PRIMARY KEY (
 M_COUPON_NO,
 M_PRODUCT_CODE
);

ALTER TABLE M_ASK ADD CONSTRAINT PK_M_ASK PRIMARY KEY (
 M_ASK_NO,
 M_CUSTOMER_ID,
 M_PRODUCT_CODE
);

ALTER TABLE M_REVIEW ADD CONSTRAINT PK_M_REVIEW PRIMARY KEY (
 M_REVIEW_NO,
 M_CUSTOMER_ID,
 M_PRODUCT_CODE
);

ALTER TABLE M_DELIVERY ADD CONSTRAINT PK_M_DELIVERY PRIMARY KEY (
 M_OPRDER_NO
);

ALTER TABLE M_ORDERPROD ADD CONSTRAINT PK_M_ORDERPROD PRIMARY KEY (
 M_ORDERPROD_NO,
 M_ORDER_NO,
 M_ORDERPROD_CODE,
 M_CUSTOMER_ID
);

ALTER TABLE M_EVENT ADD CONSTRAINT PK_M_EVENT PRIMARY KEY (
 M_EVENT_NO
);

ALTER TABLE M_PACKAGE ADD CONSTRAINT PK_M_PACKAGE PRIMARY KEY (
 M_PACKAGE_NO,
 M_PRODUCT_CODE,
 M_SEASON_NO
);

ALTER TABLE M_ADDRBOOK ADD CONSTRAINT PK_M_ADDRBOOK PRIMARY KEY (
 M_ADDRBOOK_NO,
 M_CUSTOMER_ID
);

ALTER TABLE M_CUSTOMER_COUPON ADD CONSTRAINT PK_M_CUSTOMER_COUPON PRIMARY KEY (
 Key,
 M_CUSTOMER_ID,
 M_COUPON_NO
);

ALTER TABLE M_SEASONTONE ADD CONSTRAINT PK_M_SEASONTONE PRIMARY KEY (
 M_SEASONTONE_NO
);

ALTER TABLE M_ANSWER ADD CONSTRAINT PK_M_ANSWER PRIMARY KEY (
 M_ANSWER_NO,
 M_ASK_NO
);

ALTER TABLE H_CUSTOMER ADD CONSTRAINT FK_H_COUPON_TO_H_CUSTOMER_1 FOREIGN KEY (
 H_COUPON_NO
)
REFERENCES H_COUPON (
 H_COUPON_NO
);

ALTER TABLE P_MEMBER ADD CONSTRAINT FK_H_COUPON_TO_P_MEMBER_1 FOREIGN KEY (
 P_COUPON_NO
)
REFERENCES H_COUPON (
 H_COUPON_NO
);

ALTER TABLE P_RESULT ADD CONSTRAINT FK_P_COLOR_TO_P_RESULT_1 FOREIGN KEY (
 P_COLOR_CODE
)
REFERENCES P_COLOR (
 P_COLOR_CODE
);

ALTER TABLE P_RESULT ADD CONSTRAINT FK_P_MEMBER_TO_P_RESULT_1 FOREIGN KEY (
 P_MEMBER_ID
)
REFERENCES P_MEMBER (
 P_MEMBER_EMAIL
);

ALTER TABLE P_RESULT ADD CONSTRAINT FK_M_PACKAGE_TO_P_RESULT_1 FOREIGN KEY (
 P_COLOR_NO
)
REFERENCES M_PACKAGE (
 M_PACKAGE_NO
);

ALTER TABLE P_RESULT ADD CONSTRAINT FK_M_PACKAGE_TO_P_RESULT_2 FOREIGN KEY (
 M_SEASON_NO
)
REFERENCES M_PACKAGE (
 M_SEASON_NO
);

ALTER TABLE M_CUSTOMER ADD CONSTRAINT FK_M_SEASONTONE_TO_M_CUSTOMER_1 FOREIGN KEY (
 M_SEASONTONE_NO
)
REFERENCES M_SEASONTONE (
 M_SEASONTONE_NO
);

ALTER TABLE M_ORDER ADD CONSTRAINT FK_M_CUSTOMER_TO_M_ORDER_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_ORDER ADD CONSTRAINT FK_M_CUSTOMER_TO_M_ORDER_2 FOREIGN KEY (
 M_SEASONTONE_NO
)
REFERENCES M_CUSTOMER (
 M_SEASONTONE_NO
);

ALTER TABLE M_PRODUCT ADD CONSTRAINT FK_M_SEASONTONE_TO_M_PRODUCT_1 FOREIGN KEY (
 M_SEASONTONE_NO
)
REFERENCES M_SEASONTONE (
 M_SEASONTONE_NO
);

ALTER TABLE M_COUPON ADD CONSTRAINT FK_M_PRODUCT_TO_M_COUPON_1 FOREIGN KEY (
 M_PRODUCT_CODE
)
REFERENCES M_PRODUCT (
 M_PRODUCT_CODE
);

ALTER TABLE M_ASK ADD CONSTRAINT FK_M_CUSTOMER_TO_M_ASK_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_ASK ADD CONSTRAINT FK_M_PRODUCT_TO_M_ASK_1 FOREIGN KEY (
 M_PRODUCT_CODE
)
REFERENCES M_PRODUCT (
 M_PRODUCT_CODE
);

ALTER TABLE M_REVIEW ADD CONSTRAINT FK_M_CUSTOMER_TO_M_REVIEW_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_REVIEW ADD CONSTRAINT FK_M_PRODUCT_TO_M_REVIEW_1 FOREIGN KEY (
 M_PRODUCT_CODE
)
REFERENCES M_PRODUCT (
 M_PRODUCT_CODE
);

ALTER TABLE M_ORDERPROD ADD CONSTRAINT FK_M_ORDER_TO_M_ORDERPROD_1 FOREIGN KEY (
 M_ORDER_NO
)
REFERENCES M_ORDER (
 M_ORDER_NO
);

ALTER TABLE M_ORDERPROD ADD CONSTRAINT FK_M_PRODUCT_TO_M_ORDERPROD_1 FOREIGN KEY (
 M_ORDERPROD_CODE
)
REFERENCES M_PRODUCT (
 M_PRODUCT_CODE
);

ALTER TABLE M_ORDERPROD ADD CONSTRAINT FK_M_CUSTOMER_TO_M_ORDERPROD_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_PACKAGE ADD CONSTRAINT FK_M_PRODUCT_TO_M_PACKAGE_1 FOREIGN KEY (
 M_PRODUCT_CODE
)
REFERENCES M_PRODUCT (
 M_PRODUCT_CODE
);

ALTER TABLE M_PACKAGE ADD CONSTRAINT FK_M_PRODUCT_TO_M_PACKAGE_2 FOREIGN KEY (
 M_SEASON_NO
)
REFERENCES M_PRODUCT (
 M_SEASONTONE_NO
);

ALTER TABLE M_ADDRBOOK ADD CONSTRAINT FK_M_CUSTOMER_TO_M_ADDRBOOK_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_CUSTOMER_COUPON ADD CONSTRAINT FK_M_CUSTOMER_TO_M_CUSTOMER_COUPON_1 FOREIGN KEY (
 M_CUSTOMER_ID
)
REFERENCES M_CUSTOMER (
 M_CUSTOMER_ID
);

ALTER TABLE M_CUSTOMER_COUPON ADD CONSTRAINT FK_M_COUPON_TO_M_CUSTOMER_COUPON_1 FOREIGN KEY (
 M_COUPON_NO
)
REFERENCES M_COUPON (
 M_COUPON_NO
);

ALTER TABLE M_ANSWER ADD CONSTRAINT FK_M_ASK_TO_M_ANSWER_1 FOREIGN KEY (
 M_ASK_NO
)
REFERENCES M_ASK (
 M_ASK_NO
);
